name: vaultwarden
services:
  vaultwarden:
    image: docker.io/vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN} #"https://vw.domain.tld"
    volumes:
      - podme-vaultwarden-vw-data:/data/
    ports:
      - 8000:80
volumes:
  podme-vaultwarden-vw-data:
