name: vaultwarden
services:
  vaultwarden:
    image: docker.io/vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "${DOMAIN}" #"https://vw.domain.tld"
      SIGNUPS_ALLOWED: "true"
    volumes:
      - podme-vaultwarden-vw-data:/data/
    ports:
      - 127.0.0.1:11001:80
volumes:
  podme-vaultwarden-vw-data:
