name: nextcloud
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - MYSQL_DATABASE=nextcloud
      # - MYSQL_USER=nextcloud
      # - MYSQL_PASSWORD=nextcloud
    volumes:
      - nextcloud-config:/config
      - nextcloud-data:/data
      # - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - nextcloud-mariadb-config:/config
    restart: unless-stopped

  # collabora:
  #   image: collabora/code:latest
  #   container_name: collabora
  #   environment:
  #     - aliasgroup1=https://nextcloud.mydomain.com:443
  #     - DONT_GEN_SSL_CERT=YES
  #     - extra_params=--o:ssl.enable=false --o:ssl.termination=true
  #   ports:
  #     - 9980:9980
  #   # cap_add:
  #   #   - MKNOD
  #   restart: unless-stopped

volumes:
  nextcloud-data:
  nextcloud-config:
  nextcloud-mariadb-config:
