name: jellyfin

services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - "podme-jellyfin-config:/config"
      - "podme-jellyfin-cache:/cache"
      - "podme-jellyfin-media:/media"

volumes:
  podme-jellyfin-cache:
  podme-jellyfin-config:
  podme-jellyfin-media:
